export const testimonials = [
  {
    quote: "Notamos un cambio real: Más consultas, más movimiento y sobretodo, más ventas",
    desktopLines: ["Notamos un cambio real:", "Más consultas, más movimiento", "y sobretodo, más ventas"],
    name: "Pablo Avila",
    role: "Coordinador de CYL S.A.",
    image: "/media/testimonials/cylsa-image.webp",
    avatar: "/media/testimonials/cylsa-avatar.webp",
    video: "/media/testimonials/cylsa.mp4",
    site: "https://www.cylneumaticos.com.ar/",
    alt: "Pablo Avila en las oficinas de CYL S.A.",
  },
  {
    quote: "Entendieron que quería transmitir e hicieron un trabajo excepcional y súper rápido. 100% recomendados",
    desktopLines: ["Entendieron que quería transmitir", "e hicieron un trabajo excepcional", "y súper rápido. 100% recomendados"],
    name: "Vanesa Vila",
    role: "Fundadora de Sphere Design",
    image: "/media/testimonials/sphere-design-image.jpg",
    avatar: "/media/testimonials/sphere-design-avatar.png",
    video: "/media/testimonials/sphere-design.mp4",
    site: null,
    alt: "Vanesa Vila, fundadora de Sphere Design",
  },
  {
    quote: "Entienden tu negocio y lo transforman en una web que te ayuda a potenciarte",
    desktopLines: ["Entienden tu negocio y lo", "transforman en una web", "que te ayuda a potenciarte"],
    name: "Helvio Frieiro",
    role: "Fundador de STROMA",
    image: "/media/testimonials/helvio-frieiro-image.webp",
    avatar: "/media/testimonials/helvio-frieiro-avatar.webp",
    video: "/media/testimonials/helvio-frieiro.mp4",
    site: "https://stromaservices.com/",
    alt: "Helvio Frieiro, fundador de STROMA",
  },
  {
    quote: "En Estudio Ideamos desde el primer momento entendieron que estaba buscando",
    desktopLines: ["En Estudio Ideamos desde el", "primer momento entendieron", "que estaba buscando"],
    name: "Rodolfo Merino",
    role: "Gerente de MR Ingeniería",
    image: "/media/testimonials/mr-image.webp",
    avatar: "/media/testimonials/mr-avatar.webp",
    video: "/media/testimonials/mr.mp4",
    site: "https://mringenieriaestructural.com.ar/",
    alt: "Rodolfo Merino de MR Ingeniería",
  },
  {
    quote: "Nos acompañaron e hicieron un trabajo muy profesional. Les recomiendo a Ideamos",
    desktopLines: ["Nos acompañaron e hicieron", "un trabajo muy profesional.", "Les recomiendo a Ideamos"],
    name: "Berenice Cura",
    role: "Presidente Comunidad Sorda e Hipoacúsica Tandilense",
    image: "/media/testimonials/berenice-cura-image.webp",
    avatar: "/media/testimonials/berenice-cura-avatar.webp",
    video: "/media/testimonials/berenice-cura.mp4",
    site: "https://estudioideamos.github.io/berenice-cura/",
    alt: "Berenice Cura, Presidente de la Comunidad Sorda e Hipoacúsica Tandilense",
  },
] as const;
